steps:
  - name: Example Test
    command: echo "Hello!"
  - name: gradlebuild
    command: "./gradlew clean packDeb && buildkite-agent artifact upload build/distributions/*.deb"
    agents:
      queue: 'docker'
  - name: bake
    command: 'scripts/buildkite_docker_bake.sh' 
    agents:
      queue: 'default'
